name: build_and_upload_release

on:
  pull_request:
  push: {% raw %}{{% endraw %} branches: {{ cookiecutter.default_git_branch }}{% raw %}}{% endraw %}

jobs:
  build:
    name: build and upload release
    # permit release uploads only from the repository owner
    if: github.repository == '{{ cookiecutter.git_username }}/{{ cookiecutter.git_repo }}'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2

      - name: install latest pip, setuptools, twine + wheel
        run: |
          python -m pip install --upgrade pip setuptools twine wheel

      - name: build wheels
        run: |
          python setup.py bdist_wheel
          python setup.py sdist

      - name: upload to pypi via twine
        env:
          TWINE_PASSWORD: {% raw %}${{ secrets.PYPI_TOKEN }}{% endraw %}
        run: |
          twine upload --verbose -u '__token__' dist/*

      - name: upload binaries into release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          file: dist/*
          tag: {% raw %}${{ github.ref }}{% endraw %}
          overwrite: true
          file_glob: true