name: test_coverage

on: [push]


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    steps:
      - uses: actions/checkout@v2

      - name: set up python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v2
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: install dependencies
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
              python -m pip install --upgrade pip
              pip install -e .
              pip install -r requirements_test.txt
          else
              make venv
          fi
        shell: bash

      - name: build coverage file
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            pytest --cache-clear --cov={{cookiecutter.package_slug}} tests/ > pytest-coverage.txt
          else
            make test
          fi
        shell: bash
